# Generated by Django 4.2.1 on 2024-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PRF_test',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
