# Generated by Django 4.2.1 on 2024-11-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0002_profile_prf_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='PRF_test',
        ),
    ]
