# Generated by Django 4.2.1 on 2025-07-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logSystemApp', '0003_alter_log_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=6),
        ),
    ]
